# Generated by Django 4.2.15 on 2024-09-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
