# Generated by Django 4.2.15 on 2024-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_invoice_order_transaction_orderitem_invoice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Authority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
